{
  description = "FPL: one dev shell for the harness and every implementation worktree";

  # nixpkgs straight from nixos.org, not from a forge. The channel URL moves, but
  # `nix flake lock` pins the immutable releases.nixos.org tarball behind it (revision
  # and hash are in flake.lock), so the environment does not depend on GitHub being
  # reachable. Bump with `nix flake update`.
  inputs.nixpkgs.url = "https://channels.nixos.org/nixos-26.05/nixexprs.tar.xz";

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "aarch64-darwin"
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      # Opt-in layers on top of the default shell. DATA ONLY: a name (letters and digits),
      # a description, packages, and optionally `extends`, naming layers whose packages come
      # along. Today every layer is a forge client, because nothing that talks to a forge
      # belongs in the default shell (docs/DEVSHELL.md). To add a layer, add an entry here;
      # the shells and the list .envrc checks against are generated below.
      layers = pkgs: {
        github = {
          description = "GitHub's CLI (gh)";
          packages = [ pkgs.gh ];
        };
        gitlab = {
          description = "GitLab's CLI (glab)";
          packages = [ pkgs.glab ];
        };
        radicle = {
          description = "Radicle's CLI and node (rad, radicle-node, git-remote-rad)";
          packages = [ pkgs.radicle-node ];
        };
        pijul = {
          description = "pijul, for scripts/mirror and scripts/import-pr";
          packages = [ pkgs.pijul ];
        };
        radicleui = {
          description = "Radicle's desktop app, for reviewing patches; large";
          extends = [ "radicle" ];
          packages = [ pkgs.radicle-desktop ];
        };
        forges = {
          description = "every forge client (not the desktop app)";
          extends = [
            "github"
            "gitlab"
            "radicle"
          ];
          packages = [ ];
        };
      };

      # Flattens `extends` into one package list per layer, so nothing downstream knows about
      # inheritance. The graph may be a DAG; `unique` drops what is reached twice. A cycle or
      # an unknown name throws with the path that led there. Plain recursion would instead
      # hang the evaluator, which looks like a wedged machine rather than a bad config.
      resolveLayers =
        raw:
        let
          inherit (nixpkgs.lib)
            concatMap
            concatStringsSep
            elem
            hasInfix
            mapAttrs
            unique
            ;
          packagesOf =
            seen: name:
            if elem name seen then
              throw "layer cycle: ${concatStringsSep " -> " (seen ++ [ name ])}"
            else if !(raw ? ${name}) then
              throw "unknown layer '${name}', named by: ${concatStringsSep " -> " seen}"
            else
              let
                layer = raw.${name};
                inherited = concatMap (packagesOf (seen ++ [ name ])) (layer.extends or [ ]);
              in
              inherited ++ layer.packages;
          badNames = builtins.filter (hasInfix "-") (builtins.attrNames raw);
        in
        if badNames != [ ] then
          throw "a layer name may not contain '-', which joins names: ${toString badNames}"
        else
          mapAttrs (name: layer: {
            inherit (layer) description;
            packages = unique (packagesOf [ ] name);
          }) raw;

      # The one place the line limits live. Everything that states one is generated from here
      # by `nix run .#gen-config`: .editorconfig, quality/ruff-limits.toml (which
      # quality/ruff.toml extends) and .githooks/commit-limits (which .githooks/commit-rules
      # sources). The generated files stay committed, for a clone without Nix, and
      # `make gates` fails when one differs from what this file says. A limit changes here, in
      # a harness commit, and `nix run .#gen-config` rewrites the rest.
      limits = {
        python.lineLength = 100; # quality/ruff.toml: ruff's line-length, the formatter's width
        commit = {
          header = 72; # the whole title line, <type>(<scope>): <summary>
          body = 72; # every line below it, fenced code and the like aside (docs/COMMITS.md)
        };
      };

      # The generated files, path from the repository root to contents. Each opens with the
      # same notice in its own comment syntax.
      generated =
        let
          notice = c: "${c} generated by nix run .#gen-config from lib.limits in flake.nix; do not edit\n";
        in
        {
          # EditorConfig has one max_line_length per file, so COMMIT_EDITMSG gets the smaller
          # of the two commit limits: the stricter one is the one an editor must show.
          ".editorconfig" = ''
            ${notice "#"}# EditorConfig (https://editorconfig.org): editors that read it show the
            # commit-message limit of docs/COMMITS.md. EditorConfig has one limit per
            # file, so a separate limit for the title line cannot be expressed here;
            # the commit-msg hook gates it.
            root = true

            # Git's message buffer. For a linked worktree, git keeps the file under the
            # primary checkout's .git/worktrees/<name>/, so editors read the
            # .editorconfig of whatever branch the primary checkout has out.
            [COMMIT_EDITMSG]
            max_line_length = ${toString (nixpkgs.lib.min limits.commit.header limits.commit.body)}

            # quality/ruff.toml extends quality/ruff-limits.toml, which holds line-length.
            [*.py]
            max_line_length = ${toString limits.python.lineLength}
          '';

          # ruff reads this through `extend` in quality/ruff.toml, so that file stays
          # hand-written and carries only this key from here.
          "quality/ruff-limits.toml" = ''
            ${notice "#"}line-length = ${toString limits.python.lineLength}
          '';

          # Sourced by .githooks/commit-rules, which stays hand-written.
          ".githooks/commit-limits" = ''
            # shellcheck shell=bash disable=SC2034 # the variables are the interface: commit-rules sources this file
            ${notice "#"}COMMIT_HEADER_MAX=${toString limits.commit.header}
            COMMIT_BODY_MAX=${toString limits.commit.body}
          '';
        };

      # nix run .#gen-config [-- DIR | --check]
      #   (no argument)  write the generated files into the repository this is run in
      #   DIR            write them under DIR instead (a scratch tree, to compare with)
      #   --check        write nothing; exit 1 and name the files that differ from the
      #                  repository's. This is what `make gates` runs.
      genConfig =
        pkgs:
        pkgs.writeShellApplication {
          name = "gen-config";
          runtimeInputs = [
            pkgs.coreutils
            pkgs.diffutils
            pkgs.git
          ];
          text = ''
            top="$(git rev-parse --show-toplevel)"
            mode="write"
            dest="$top"
            case "''${1:-}" in
            "") ;;
            --check) mode="check" ;;
            -*)
              echo "usage: nix run .#gen-config [-- DIR | --check]" >&2
              exit 2
              ;;
            *) dest="$1" ;;
            esac
            if [ "$mode" = check ]; then
              dest="$(mktemp -d)"
              trap 'rm -rf "$dest"' EXIT
            fi

            ${nixpkgs.lib.concatStrings (
              nixpkgs.lib.mapAttrsToList (path: text: ''
                install -D -m 0644 ${pkgs.writeText "gen-config-file" text} "$dest/${path}"
              '') generated
            )}
            if [ "$mode" = check ]; then
              stale=0
              unmarked=0
              for f in ${nixpkgs.lib.concatStringsSep " " (builtins.attrNames generated)}; do
                if ! cmp -s "$dest/$f" "$top/$f"; then
                  echo "gen-config: $f differs from what lib.limits in flake.nix generates:" >&2
                  if [ -e "$top/$f" ]; then
                    diff -u "$top/$f" "$dest/$f" >&2 || true
                  else
                    echo "  (the file does not exist)" >&2
                  fi
                  stale=1
                fi
                case "$(git -C "$top" check-attr linguist-generated -- "$f")" in
                *": true") ;;
                *)
                  echo "gen-config: .gitattributes does not mark $f linguist-generated=true" >&2
                  unmarked=1
                  ;;
                esac
              done
              if [ "$stale" = 1 ]; then
                echo "gen-config: run  nix run .#gen-config  and commit the result" >&2
              fi
              if [ "$unmarked" = 1 ]; then
                echo "gen-config: add the line  <file> linguist-generated=true  to .gitattributes" >&2
              fi
              [ "$stale$unmarked" = 00 ] || exit 1
            fi
          '';
        };
    in
    {
      devShells = forAllSystems (
        pkgs:
        let
          # Everything the harness and an implementation worktree need, and nothing that
          # talks to a forge: the default shell must be enough to do all the work offline
          # and against any remote.
          base = [
            # The harness: scripts/ and .githooks/ are bash >= 4 (mapfile) and were written
            # against GNU userland; macOS ships bash 3.2 and BSD tools.
            pkgs.bashInteractive
            pkgs.coreutils
            pkgs.gnugrep
            pkgs.gnused
            pkgs.gawk
            pkgs.git
            pkgs.jujutsu # optional workflow, docs/JJ.md
            pkgs.diff2html-cli # scripts/review renders a branch as a page
            # scripts/leak-check, which the hooks run on every commit and push: the
            # repository is public, so it cannot wait in an opt-in layer.
            pkgs.gitleaks

            # The implementation stack, docs/STACK.md, and the noslop gate, docs/QUALITY.md.
            # A bare Python 3.12, and uv, which syncs Lark and the gate's Python tools into
            # each worktree's .venv at the versions quality/uv.lock pins: several of them
            # (import-linter, deptry, CrossHair) are not in nixpkgs. pyright stays here,
            # since it is a Node program; ruff too, for the root and for editors.
            pkgs.python312
            pkgs.uv
            pkgs.ruff
            pkgs.pyright
            pkgs.gnumake
          ];

          mkFplShell =
            extra:
            pkgs.mkShell {
              packages = base ++ extra;

              # uv uses the shell's Python and never downloads one of its own.
              UV_PYTHON = "${pkgs.python312}/bin/python3.12";
              UV_PYTHON_DOWNLOADS = "never";

              # Wire the git hooks once per clone/worktree; stay silent afterwards so that
              # direnv re-entering the shell costs nothing.
              shellHook = ''
                ${pkgs.lib.optionalString pkgs.stdenv.isLinux ''
                  # CrossHair's solver, z3, comes as a PyPI wheel linked against libstdc++,
                  # which a Nix Python does not put on the loader path (make harden).
                  export LD_LIBRARY_PATH="${pkgs.stdenv.cc.cc.lib}/lib''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
                ''}
                if top="$(git rev-parse --show-toplevel 2>/dev/null)" \
                  && [ -x "$top/scripts/setup" ] \
                  && [ "$(git config --local --get core.hooksPath 2>/dev/null)" != ".githooks" ]; then
                  "$top/scripts/setup"
                fi
              '';
            };
        in
        # One shell per combination of layers, named by the layer names in sorted order joined
        # with "-": default, github, github-gitlab, ... Attributes are lazy, so a combination
        # nobody asks for is never evaluated. .envrc builds the same name from .fpl-shell.
        let
          inherit (nixpkgs.lib) concatMap foldl unique;
          resolved = resolveLayers (layers pkgs);
          names = builtins.attrNames resolved;
          subsets = foldl (acc: n: acc ++ map (s: s ++ [ n ]) acc) [ [ ] ] names;
          shellFor = subset: {
            name = if subset == [ ] then "default" else builtins.concatStringsSep "-" subset;
            value = mkFplShell (unique (concatMap (n: resolved.${n}.packages) subset));
          };
        in
        builtins.listToAttrs (map shellFor subsets)
      );

      # What layers exist, without building anything: `nix eval --json .#lib.layers`.
      # .envrc checks .fpl-shell against `layerNames`. Only names and descriptions are forced,
      # so the empty package set is never looked into.
      lib.layers = builtins.mapAttrs (_: layer: layer.description) (layers { });
      lib.layerNames = builtins.concatStringsSep " " (builtins.attrNames (layers { }));

      # The line limits, one source (see `limits` above): `nix eval --json .#lib.limits`.
      lib.limits = limits;

      apps = forAllSystems (pkgs: {
        gen-config = {
          type = "app";
          program = "${genConfig pkgs}/bin/gen-config";
          meta.description = "Write the files generated from lib.limits (--check: only compare)";
        };
      });

      formatter = forAllSystems (pkgs: pkgs.nixfmt);
    };
}
